# Dicionário para traduzir os nomes das features para os gráficos
FEATURE_TRANSLATOR = {
    "anxiety_level": "Nível de Ansiedade",
    "self_esteem": "Nível de Autoestima",
    "mental_health_history": "Histórico de Saúde Mental",
    "depression": "Nível de Depressão",
    "headache": "Frequência de Dor de Cabeça",
    "blood_pressure": "Pressão Sanguínea",
    "sleep_quality": "Qualidade do Sono",
    "breathing_problem": "Problemas Respiratórios",
    "noise_level": "Nível de Ruído",
    "living_conditions": "Condições de Moradia",
    "safety": "Sensação de Segurança",
    "basic_needs": "Atendimento de Necessidades Básicas",
    "academic_performance": "Desempenho Acadêmico",
    "study_load": "Carga de Estudos",
    "teacher_student_relationship": "Relação Professor-Aluno",
    "future_career_concerns": "Preocupações com a Carreira",
    "social_support": "Suporte Social",
    "peer_pressure": "Pressão dos Colegas",
    "extracurricular_activities": "Atividades Extracurriculares",
    "bullying": "Frequência de Bullying",
    "stress_level": "Nível de Estresse",
}
